[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Stripe publishable keys are meant to be public - exclude from secret scanning
[context.production.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/**,node_modules/**"

[context.deploy-preview.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/**,node_modules/**"

[context.branch-deploy.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/**,node_modules/**"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
