[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Disable secret detection - Stripe publishable keys are meant to be public
[context.production.environment]
  NETLIFY_SKIP_SECRET_DETECTION = "true"

[context.deploy-preview.environment]
  NETLIFY_SKIP_SECRET_DETECTION = "true"

[context.branch-deploy.environment]
  NETLIFY_SKIP_SECRET_DETECTION = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
